version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "digital-twin-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1g1z12912s9ii"
s3_prefix = "digital-twin/dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=dev"
