name: Deploy Dev Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup SAM
        uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ##region##
      - name: Build
        run: sam build --beta-features
      - name: Deploy dev
        run: sam deploy --config-env dev
