name: Pull Request Open Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup SAM
        uses: aws-actions/setup-sam@v1
      - name: Build
        run: sam build --beta-features
      - name: Install dependencies
        run: npm ci --prefix hello-world
      - name: Test
        run: npm test --prefix hello-world
